channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.6
  - pandas=1.1.5
  - bioconda::snakemake-minimal=6.0.3
  - matplotlib=3.3.1
  - graphviz=2.38.0
  - bioconda::bcftools=1.9
  - bioconda::samtools=1.9
  - bwa=0.7.17
  - pysam=0.15.0
  - conda-forge::ete3=3.1.2
  - bioconda::pyvcf=0.6.8
  - bioconda::bedtools=2.30.0
