channels:
  - conda-forge
  - bioconda
dependencies:
  - pandas =1.1.1
  - bioconda::snakemake-minimal =5.22.1
  - matplotlib =3.3.1
  - graphviz =2.38.0
  - bioconda::bcftools =1.9
  - bioconda::samtools =1.9
  - bwa =0.7.17
  - pysam =0.15.0
