# Mycobacteroides NCBItaxid:670516
target_species_taxid: 670516
# copy into resources directory - provide your own, due to license
gatk3_jar: "GenomeAnalysisTK.jar"
# base location of internal sample read data
data_dir: "/media/nick/8TB/SGL_MA/"
# Replace this with the sample sheet for your own samples, see provided example
# for the format
sample_sheet: "samples.test.yaml"
# copied from a local installation of Trimmomatic - don't know where the
# adapter files live in conda-land
adapters_fasta: "resources/TruSeq3-PE.fa"
# minimum length of read to keep - see Martin et al 2018, referenced in Lee et al 2020
QC_min_length: 36
# a directory, downloaded from kraken2 ftp - see Required Files in readme.md
kraken_db: "minikraken2_v2_8GB_201904_UPDATE/"
# This is on a fast SSD, shovill faster
shovill_tempdir: "/home/nick/Downloads/tmp"
# A tempdir can get quite large, running out of space is a failure point
mashtree_tempdir: "mashtree_tmp"
# This sequence is the definitional Erm(41) in Nash et al 2009 (PMID:19171799)
erm41_query: "resources/Erm41.fa"
# <https://www.ncbi.nlm.nih.gov/nuccore/NC_000962.3>
outgroup_assembly: "GCF_000195955.2"
# directroy for all results
results_dir: "results"
# default mash taxa bolettii, mmas, abscessus
mash_ref_taxa: ['GCF_003609715.1', 'GCF_000497265.2', 'GCF_001942505.1']
# samples to exclude in stage 2
exclude_samples: []